### ISSUE TITLE
[REQUEST] Hide description field in card if no description exists

### ISSUE THREAD

**Issue by asakura42** [Lyaaaaaaaaaaaaaaa/Project_Kanban#9]

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hi, this is a good idea. I'm actually working on other projects.
Though, I'm adding this idea to the TO DO list. I'm not sure if it's even possible with GTK-3 to hide this field but I will search.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
The description field is now hidden if there is no description.
See pull request https://github.com/Lyaaaaaaaaaaaaaaa/Project_Kanban/pull/10
